-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:fddbeb0d474174f38c0fd1010eb9eecb:a7583183347e5cd695df8a48dd4b0425:46e8202e3364549de521113252aeb411$
-- 

return {
	texture = 'entities2.png',
	frames = {
			{
				name = "Death001.png",
				spriteColorRect = { x = 86, y = 48, width = 74, height = 100 },
				uvRect = { u0 = 0.898936, v0 = 0.016129, u1 = 0.99734, v1 = 0.822581 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death002.png",
				spriteColorRect = { x = 72, y = 30, width = 78, height = 118 },
				uvRect = { u0 = 0.792553, v0 = 0.016129, u1 = 0.896277, v1 = 0.967742 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death003.png",
				spriteColorRect = { x = 62, y = 30, width = 102, height = 118 },
				uvRect = { u0 = 0.332447, v0 = 0.016129, u1 = 0.468085, v1 = 0.967742 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death004.png",
				spriteColorRect = { x = 52, y = 28, width = 98, height = 120 },
				uvRect = { u0 = 0.659574, v0 = 0.016129, u1 = 0.789894, v1 = 0.983871 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death005.png",
				spriteColorRect = { x = 38, y = 34, width = 112, height = 114 },
				uvRect = { u0 = 0.00265957, v0 = 0.016129, u1 = 0.151596, v1 = 0.935484 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death006.png",
				spriteColorRect = { x = 18, y = 52, width = 132, height = 96 },
				uvRect = { u0 = 0.154255, v0 = 0.016129, u1 = 0.329787, v1 = 0.790323 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death007.png",
				spriteColorRect = { x = 10, y = 64, width = 140, height = 84 },
				uvRect = { u0 = 0.470745, v0 = 0.016129, u1 = 0.656915, v1 = 0.693548 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death008.png",
				spriteColorRect = { x = 46, y = 122, width = 104, height = 26 },
				uvRect = { u0 = 0.470745, v0 = 0.709677, u1 = 0.609043, v1 = 0.919355 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "Death009.png",
				spriteColorRect = { x = 46, y = 122, width = 104, height = 26 },
				uvRect = { u0 = 0.470745, v0 = 0.709677, u1 = 0.609043, v1 = 0.919355 },
				spriteSourceSize = { width = 276, height = 176 },
				spriteTrimmed = true,
				textureRotated = false
			},
		}
	}
